### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by DutchPete** [Bluemoondragon07/obsidian-big-and-bold#5]
![image](https://user-images.githubusercontent.com/10794265/224980133-d611b2fd-ccde-4122-b3d8-3ccfdb2b81bb.png)

Scrollbars are visible and look ugly. I noticed in your screenshots there are no scrollbars, though perhaps only on hover.

How can I achieve that too? There does not seem to be a setting for it in Style Settings.
I am on MacOS, Obsidian 1.1.16.

**Comment by Bluemoondragon07** [comment]
Hmm, that's strange. I thought I did remove scrollbars, but they must be entirely different on Mac. Is that what scrollbars look like in most themes? If not, maybe I removed the Obsidian scrollbars and left native scrollbars visible.

Anyhow, I'll get this fixed. There's definitely a snippet somewhere I can look at for hiding scrollbars on Mac.

**Comment by DutchPete** [comment]
Yes, those scrollbars look like that in other themes too.

I can make them disappear with this:

```css
::-webkit-scrollbar {
  width: 0;
}
```

or with this

```css
::-webkit-scrollbar {
  opacity: 0;
}
```

but in either case I cannot make them appear on hover, even with e.g. this:

```css
::-webkit-scrollbar:hover {
  opacity: 1;
}
```
