### ISSUE TITLE
Improved ribbon menu width

### ISSUE THREAD

**Issue by LeslyeCream** [Bluemoondragon07/obsidian-big-and-bold#8]
Your theme is really impressive! it has made me want to use obsidian again. 

I think the ribbon menu could be improved a bit by adjusting its width:

![IMG_20230410_173932](https://user-images.githubusercontent.com/81089188/231012381-0471264d-83e2-44d8-8d15-a85d4aa6af87.jpg)
![IMG_20230410_173910](https://user-images.githubusercontent.com/81089188/231012407-ec3cbcb2-2296-4298-a536-2bd2f37d1413.jpg)

I have used the following code 

`.is-mobile .menu { max-height: calc(100% - 100px); width: calc(100% - 40px); max-width: calc(90% - 20px); min-width: unset; position: absolute; bottom: 0; border-radius: 9px 9px 0 0; padding: 10px 20px; left: 10px !important; top: unset !important; overflow-y: auto; }` 

I think it needs just one adjustment as you can see in the screenshot (it doesn't quite match the width of the text).

Otherwise it's perfect for me 💯 Thank you ! 

Bwt: how can I easily change the color or transparency of the text (inline title and content). I have tried with snippets but it doesn't work and within the RGB it makes me completely lost 😂

**Comment by Bluemoondragon07** [comment]
Hi, glad you like the theme! The messed up prompt width is actually leftover code that I forgot to delete when I was planning to redesign the mobile interface a bit more than I ended up doing. A quick fix would be this snippet, but I'll also fix it in the next update:

```css
.is-phone .prompt {
width: 100vh;
}
```

And for changing the opacity of the text, you could use this snippet: 

```css
body {
    --text-opacity: 0.5; /* <-- put desired opacity here */
}
.theme-light {
    --text-normal: rgba(0, 0, 0, var(--text-opacity)) !important;
}
.theme-dark {
    --text-normal: rgba(255, 255, 255, var(--text-opacity)) !important;
}

/*
@settings
name: Text Opacity
id: text-opacity-settings
settings:
    -
        id: text-opacity
        title: Text Opacity
        type: variable-number-slider
        default: 1
        min: 0
        max: 1
        step: 0.1
*/

```
This snippet also includes Style Settings support, so you can change the opacity that way, too.
